version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    expose: 
      - 3000
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - node_modules:${APP_CODE_PATH_CONTAINER}/node_modules


volumes:
  node_modules: